language: node_js

cache:
    directories:
        - node_modules
        - bower

node_js:
  - '0.12'

before_install:
  - npm --version

install:
  - npm install -g bower gulp-cli
  - bower install
  - npm install

script:
  - gulp test